### ISSUE TITLE
Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by saeedhei** [papandreou/node-inkscape#43]
Hello I'm using inkscape Module to convert pdf to svg and why I'm Getting `Cannot read property 'end' of undefined`

**My Code:**
```
const Inkscape = require('inkscape');

const pdfToSvgConverter = new Inkscape([
  '--export-plain-svg',
  '--import-pdf',
  '--export-text-to-path'
]);


fs.createReadStream('test/people.pdf').pipe(pdfToSvgConverter).pipe(fs.createWriteStream('./out.svg'));
```

**Comment by papandreou** [comment]
Hi @saeedhei, thanks for getting in touch! Which version of Inkscape are you using? If it's 1.0 or above, it's likely because we don't support that yet. They completely changed the CLI switches.

We're working on it: https://github.com/papandreou/node-inkscape/pull/41

Maybe you could see if that branch fixes it?

**Comment by saeedhei** [comment]
Thanks @papandreou  , I installed npm latest inkscape, I want to convert Pdf to svg in my server, Can you Help me or introduce me a module?

**Comment by papandreou** [comment]
I meant which version of Inkscape itself do you have? (not this module). You can find out by running `inkscape --version`. If it's 1.0, this module doesn't work with it yet.

**Comment by saeedhei** [comment]
If I Install Inkscape 0.92.5, then can I use this module?

**Comment by papandreou** [comment]
Yes!
