### ISSUE TITLE
How to Export svg to pdf file

### ISSUE THREAD

**Issue by usama-ayub** [papandreou/node-inkscape#7]
hi,

help me .
Example code how to convert svg to pdf

**Comment by papandreou** [comment]
There’s an example in the readme:

```js
var Inkscape = require('inkscape'),
    svgToPdfConverter = new Inkscape(['--export-pdf', '--export-width=1024']);

sourceStream.pipe(svgToPdfConverter).pipe(destinationStream);
```

You have to create `sourceStream` and `destinationStream` yourself. If you’re reading from and writing to disc, you’ll probably want to use `require(‘fs’).createReadStream(fileName)` and `createWriteStream`.

**Comment by usama-ayub** [comment]
thanks @papandreou

**Comment by usama-ayub** [comment]
hi @papandreou 
can you tell me that  it's possible to convert  svg to dxf is using this library .

**Comment by papandreou** [comment]
Hmm, I'm not sure, I've never worked with that format myself. The `inkscape` binary on my system does not mention dxf in the cli help, but when I open up the gui I am able to save to dxf.

[This article](http://www.inkscapeforum.com/viewtopic.php?t=32665) mentions that the script ps2dxf.sh might be used internally, and I do have that on my Linux box in /usr/share/inkscape/extensions/ as well as pstoedit (/usr/bin/pstoedit), which it's apparently using.

However, since dxf doesn't seem to be available in the cli interface, I think the answer is no, strictly speaking. But you might be able to convert to eps format `new Inkscape(['--export-eps'])` and then wire something up with those other scripts.

In that case this library probably doesn't bring anything to the table. You might as well just execute all those commands, including `inkscape`, in a shell script or via `require('child_process').exec`.

**Comment by usama-ayub** [comment]
hi,

thanks for your response 
can you send me sample of code 
svg to eps
